### ISSUE TITLE
Multi nanoleaf select on/off not work 

### ISSUE THREAD

**Issue by KLeval** [Baptiewright/streamdeck-nanoleaf#3]
Hi, 

I have Two nanoleaf modules and i'm trying to make 2 buttons to switch on/off my two modules distinctly. But when i choose the IP of concerned module, it dont save it. 

Please check : 

https://i.gyazo.com/4eebaab0d55b62fb99185784c40f00f7.mp4

**Comment by rainmanjam** [comment]
Same here.

**Comment by rainmanjam** [comment]
OK.. found a work around. Instead of using on/of.. Use Color and set it to black to turn it off. Works as a work around.

**Comment by JoergAp** [comment]
Any chance to get this fixed?

**Comment by Baptiewright** [comment]
Well that's a shitty bug, you'd think having 2 Nanoleafs myself I would've noticed it.  Sorry about that, I'll try to fix it this week.

**Comment by Baptiewright** [comment]
v1.4 should fix this bug, it's in the Releases section now
