### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by Total-Ecl1ps3** [Baptiewright/streamdeck-nanoleaf#5]
Have you given up this project?
It's really disappointing to see that there's a nanoleaf action in the Stream Deck program, but most parts of it doesn't work.
I see that there's 4 issues here that's been open for several months, none of them has any response from you guys, and the last repo update was over a year ago.

If you have abandoned this, then please do us all a favour and have it pulled from the Stream Deck more actions menu, so more people don't get false hope.

**Comment by Baptiewright** [comment]
"you guys" is just me, and sorry I've been dealing with a lot of personal stuff.   I stopped posting the code here because the plugin is in the official SD plugin list.  

I'll take a look at the issues, I use the plugin daily and don't have any problems.

**Comment by Baptiewright** [comment]
V1.4 released with bugfixes, if you have specific issues please open a new one.
